version: '3'

services:
  xampp:
    container_name: xampp
    image: tomsik68/xampp
    ports:
      - "8080:80"
      - "443:443"
      - "3306:3306"
    volumes:
      - ./meu_projeto:/opt/lampp/htdocs

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
